connector_image: airbyte/source-amplitude:dev
tests:
  spec:
    - spec_path: "source_amplitude/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/streams_with_output_records_catalog.json"
      validate_output_from_all_streams: yes
  incremental:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      # Unable to use 'state_path' because Amplitude returns an error when specifying a date in the future.
      # state_path: "integration_tests/abnormal_state.json"
      cursor_paths:
        events: [ "event_time" ]
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
