# See [Source Acceptance Tests](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/source-acceptance-tests.md)
# for more information about how to configure these tests
connector_image: airbyte/source-harvest:dev
tests:
  spec:
    - spec_path: "source_harvest/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "exception"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      validate_output_from_all_streams: yes
# TODO uncomment this block to specify that the tests should assert the connector outputs the records provided in the input file a file
#      expect_records:
#        path: "integration_tests/expected_records.txt"
#        extra_fields: no
#        exact_order: no
#        extra_records: yes
  incremental:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      state_path: "integration_tests/abnormal_state.json"
      cursor_paths:
        contacts: ["updated_at"]
        clients: ["updated_at"]
        invoices: ["updated_at"]
        invoice_messages: ["updated_at"]
        invoice_payments: ["updated_at"]
        invoice_item_categories: ["updated_at"]
        estimates: ["updated_at"]
        estimate_messages: ["updated_at"]
        estimate_item_categories: ["updated_at"]
        expenses: ["updated_at"]
        expense_categories: ["updated_at"]
        tasks: ["updated_at"]
        time_entries: ["updated_at"]
        user_assignments: ["updated_at"]
        task_assignments: ["updated_at"]
        projects: ["updated_at"]
        roles: ["updated_at"]
        users: ["updated_at"]
        billable_rates: ["updated_at"]
        cost_rates: ["updated_at"]
        project_assignments: ["updated_at"]
        expenses_clients: ["updated_at"]
        expenses_projects: ["updated_at"]
        expenses_categories: ["updated_at"]
        expenses_team: ["updated_at"]
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
